### ISSUE TITLE
Interested? Leave a note on here (please comment with your operating system, device type... use https://aboutmybrowser.com/ to do this easily)

### ISSUE THREAD

**Issue by mattl** [foocorp/hacienda#1]
Please note: new accounts will be given to active beta testers first. See #2 if you're interested in becoming a beta tester.

**Comment by sammypanda** [comment]
+1

**Comment by sammypanda** [comment]
count me in! \(^^)/

**Comment by virtadpt** [comment]
There is interest.

**Comment by ea-st** [comment]
_interested!_  ≥^oᆺo^≤

**Comment by genericness** [comment]
new to libre.fm but this seems interesting, interested!

**Comment by A113-187** [comment]
Count me in

**Comment by ash3T** [comment]
When the hacienda will be released?

**Comment by goodevilgenius** [comment]
I'm interested, and am a Laravel developer. I'd also like to see this be able to federate with ActivityPub servers in some capacity.

I'm imagining something that's a cross between Last.fm and Goodreads (or Bookwyrm, if you prefer). Not simply an audio scrobbling service, but also allows for reviews and a recommendation engine.

**Comment by virtadpt** [comment]
I'd be happy with a sensible REST API and Hacienda playing nicely with shared hosting.

**Comment by mattl** [comment]
> When the hacienda will be released?

There's no code at all right now. I hope to get started on this soon.

**Comment by mattl** [comment]
> I'm interested, and am a Laravel developer. I'd also like to see this be able to federate with ActivityPub servers in some capacity.
> 
> I'm imagining something that's a cross between Last.fm and Goodreads (or Bookwyrm, if you prefer). Not simply an audio scrobbling service, but also allows for reviews and a recommendation engine.

I'm not sure if this is something I want to build for Libre.fm, but I am interested in seeing how ActivityPub stuff might work. Don't forget Libre.fm/GNU FM has been federated for a very long time already.

**Comment by virtadpt** [comment]
@mattl A host that provides HTTP(S), PHP, and database services (usually MySQL) for many users on the same server (e.g., Dreamhost).  Dreamhost does offer SSH access to whatever server they assign you to, which makes many things easier.

**Comment by kinnounko** [comment]
interested! :+1:

**Comment by locness3** [comment]
Interested.

**Comment by dy75** [comment]
yes!

**Comment by madmax76** [comment]
very interested

**Comment by buergi** [comment]
Federated version of GNU FM, interesting, though I'm mostly scrobbling for myself, statistics and recommendations, so I'm not sure yet what the benefits of the fediverse will be.

**Comment by mattl** [comment]
@buergi GNU FM has been federated for over a decade. 

Anyway, I’m going to close this thread. I will be in touch soon when I have some minimal working code to show. First step is to bring over the existing database structure as migrations and then things can be extended as necessary. 

Plans have been delayed a little by the death of a close friend but I am beginning to work on this.

**Comment by mattl** [comment]
I've just pushed up https://github.com/foocorp/hacienda/commit/ec1c7ae04d10973ef9a2a89373cf110dcc22d9d8 which brings over the existing GNU FM database structure to Hacienda. From here I will start building out the logic.

**Comment by goodevilgenius** [comment]
@mattl Is the initial goal to be API compatible (with the same database structure) with GNU FM, so that Hacienda can be used as a drop-in replacement, and then build upon that?

**Comment by mattl** [comment]
@goodevilgenius Yep, API and database... so anything new will need to be in new database tables.

Something I'm trying to figure out first is an extended method for handling users. Last.fm clients and the like rely on old MD5 password hashes. I'd like to not use those for authentication to the app, but allow users to generate them inside the app for their clients. So I'm making a 'members' table which is a new table which will do the actual logging in/out of the app, while users will remain for client support. Ultimately it would be cool if users could make as many username/password combos as they have devices.

**Comment by rheaplex** [comment]
It might be worth delegating account/registration handling to a third party library?

**Comment by mattl** [comment]
It basically is. It’s something from Laravel.

**Comment by tobyink** [comment]
Count me in too. (I was a GNU FM dev back in 2009/2010.)

**Comment by mattl** [comment]
Hey Toby! Awesome to hear from you :) @tobyink

**Comment by ViStefan** [comment]
I'm in!

**Comment by girlmaya** [comment]
Interested

**Comment by tjoels** [comment]
Yes, I'm interested!

**Comment by s-light** [comment]
i'm interested.
(long time i used libre.fm daily to hear and find new wonderful music  ;-) )

> @mattl A host that provides HTTP(S), PHP, and database services (usually MySQL) for many users on the same server (e.g., Dreamhost). Dreamhost does offer SSH access to whatever server they assign you to, which makes many things easier.

most of the easier hosters do not offer ssh.
but i think a good *build* laravel deploy package should work there too....

**Comment by ronnicek** [comment]
Let's go! :)

**Comment by lopezwys** [comment]
I'm interested

**Comment by kurthbemis** [comment]
Interested.

professional sysadmin/developer/open source hacker.

**Comment by paulo-roger** [comment]
> I'm interested, and am a Laravel developer. I'd also like to see this be able to federate with ActivityPub servers in some capacity.
> 
> I'm imagining something that's a cross between Last.fm and Goodreads (or Bookwyrm, if you prefer). Not simply an audio scrobbling service, but also allows for reviews and a recommendation engine.

I am also interested and see an ActivityPub implementation and am eager to help.

**Comment by millette** [comment]
I hadn't heard about the new project and yesterday, I found out about <https://github.com/krateng/maloja> which might be interesting.

**Comment by bigmanstan** [comment]
Interested.

**Comment by simonives** [comment]
Very interested.

**Comment by ZerdoX-x** [comment]
I am interested too :)
I don't remember where I found libre.fm. So.. it is not possible to register at the old libre.fm?

**Comment by brzd** [comment]
I'm in.

**Comment by thattemperature** [comment]
interested!

**Comment by SkullGamer205** [comment]
+1

**Comment by LeoTech10** [comment]
interested

**Comment by pchmykh** [comment]
+1

**Comment by 11ph22il** [comment]
+1

**Comment by xeniode** [comment]
+1

**Comment by algentok** [comment]
Let me in

**Comment by CrashBandicooch** [comment]
interested

**Comment by Milkvveed** [comment]
Why am I redirected to this page when I try to sign up for a libre.fm account? Someone help!

**Comment by mattl** [comment]
We’re no longer accepting sign ups until the new site is ready.

**Comment by jtojnar** [comment]
Until then you can use https://listenbrainz.org/ from the foundation that manages MusicBrainz. The source code is available as well: https://github.com/metabrainz/listenbrainz-server

**Comment by Jamama696969** [comment]
fn balls

**Comment by Ender0112** [comment]
Interesante

**Comment by lgxnder** [comment]
Interested!

**Comment by alexweber** [comment]
+1

**Comment by TheFastBadger** [comment]
Noted.

**Comment by adityadewhy** [comment]
interested

**Comment by stardustspirit** [comment]
interest is present!

**Comment by GautamSingh6599** [comment]
Interested !!!

**Comment by maziogra** [comment]
I'm interested

**Comment by SamyakVasha** [comment]
im interested

**Comment by driftywinds** [comment]
I would love to register when it opens up

**Comment by alvimpaulo** [comment]
Yo

**Comment by wenneton** [comment]
I'm interested!

**Comment by talekksna** [comment]
I am very interested to have an account. So thank you very much for opportunity.

Cheers.

**Comment by MisterPerson42** [comment]
@mattl will there be integration for Rhythmbox? That's how I found my way to libre.fm. too bad they don't accept new accounts for now; I will be looking forward to when it opens up, :grin:

**Comment by pvnkrockjesvs** [comment]
Interessed

**Comment by grdryn** [comment]
I am also interested! :raising_hand:

**Comment by mgmerino** [comment]
+1

**Comment by vletard** [comment]
I am interested in getting an account, and also getting involved in the dev process if I can be of any help. This kind of project interests me. Do you have a planning, reference read for contributors to start @mattl ?

**Comment by mattl** [comment]
@vletard At this point, no. Once the development effort is underway, I'll have something... but initially I'm working on this with help from @rheaplex depending on how much time she has to work on this.

**Comment by Amine0negative** [comment]
Im really interested ! count me in

**Comment by james-jasvin** [comment]
I'm interested please notify me when registrations are open

**Comment by wolfkin** [comment]
Color me interested

**Comment by sestarus13** [comment]
Not e

**Comment by gvxvik** [comment]
count me in

**Comment by itsAllDigital** [comment]
**Lifts hand**: Yes

**Comment by yannred** [comment]
Interested

**Comment by qcmoff22** [comment]
HELLO WORLD  
![bureau](https://github.com/foocorp/hacienda/assets/95582304/715a1ba3-a700-4693-839d-9b679f05877f)

**Comment by yuugiiy** [comment]
I am interested :)

**Comment by michaelpennington** [comment]
Interest!

**Comment by urkbio** [comment]
i want to join

**Comment by Craffo** [comment]
Interested!

**Comment by fir3-1ce** [comment]
I'm interested

**Comment by xtox-io** [comment]
Me too

**Comment by XenorPLxx** [comment]
Been scrobbling since 31 May 2005, happy to check out the alternatives.

**Comment by ayojubb** [comment]
just want to try another scrobbling service, interested in registration :3

**Comment by shiftgeist** [comment]
Interested!

**Comment by eizoken** [comment]
waiting for

**Comment by pax** [comment]
+1 🤞

**Comment by augustopereiratx** [comment]
we will watch your career with great interest

**Comment by AesaraB** [comment]
Interested, would love to use this project as a way to learn more about backend stuff. Sticking with PHP or moving to a different language?

**Comment by jasondmoss** [comment]
Yep. I'm ready! Sign me up!

**Comment by saxobroko** [comment]
Note.

**Comment by jgallern** [comment]
Interested !!

**Comment by themidnightmaniac** [comment]
I'm Interested!

**Comment by iuliandita** [comment]
+1

**Comment by jason4bury** [comment]
Hi, I'm interested.

**Comment by FlitPix** [comment]
Hihi, I'm also interested!

**Comment by wafflestrom** [comment]
I'm interested

**Comment by louisgrasset** [comment]
Hey, I’d like to participate too

**Comment by winrg** [comment]
I develop [scrobble.observer](https://scrobble.observer), a last.fm widget for personal websites. I'd be interested in supporting this at some point in the future when it gets off the ground.

**Comment by r00l** [comment]
i am interested in an account please

**Comment by Honey181** [comment]
Interested

**Comment by BNH440** [comment]
I'm interested

**Comment by Shianiiiu** [comment]
Hi

**Comment by joweraDE** [comment]
```java
System.out.println("I'm in");
```

**Comment by cmgarciap** [comment]
I'm interested to register!

**Comment by hyuuwu** [comment]
sign me in :3

**Comment by Gino16** [comment]
I'm interested to register!! .

**Comment by psychonout** [comment]
would definitely like to sign-up when available!

**Comment by Jweim1983** [comment]
Id like ti sign up as well

**Comment by Bishmanrock** [comment]
I'm interested

**Comment by boormanthechauffeur** [comment]
I'm also interested

**Comment by MrCaringi** [comment]
count on me!

**Comment by victor-champonnois** [comment]
Interested!

**Comment by sthetz** [comment]
Interested. Keep up the good work!

**Comment by faq0** [comment]
Interested

**Comment by voyager** [comment]
Thanks for all the hard work. 🙌
Count me in!

**Comment by pluc** [comment]
@mattl let's go

**Comment by Droppisalt** [comment]
Interested!

**Comment by labou** [comment]
I'm interested in getting an account!

**Comment by eointhedoherty** [comment]
Interested! 🤘

**Comment by grindingrock** [comment]
Interested ☄

**Comment by AdamK2003** [comment]
def interested!

**Comment by hstriepe2** [comment]
interedasted in contributing

**Comment by shym3q** [comment]
interested

**Comment by mattl** [comment]
Just an update, you can see some work in progress open for feedback here: #12 -- please feel free to comment and check it out.

**Comment by frankpanduh** [comment]
interested

**Comment by MannuVilasara** [comment]
interested

**Comment by titanProto** [comment]
interested :3

**Comment by huangjiang-nuxia** [comment]
Count me in!

**Comment by alessandroseni** [comment]
Interested

**Comment by millette** [comment]
FYI <https://github.com/metabrainz/listenbrainz-server> is also open source (python).

**Comment by MoZiSaan** [comment]
+1

**Comment by dramonroca** [comment]
Interested

**Comment by codex78** [comment]
++

**Comment by tsnavi** [comment]
Interested in registering :)

**Comment by bretello** [comment]
+1

**Comment by StalkyBoi43815** [comment]
fuck privacy stealing corporations

**Comment by nolemoczij** [comment]
+1

**Comment by prk0ghy** [comment]
+1

**Comment by MedAmineMahmoud** [comment]
🗿

**Comment by ve3xone** [comment]
+

**Comment by SatyarajRana** [comment]
Interested

**Comment by grwthomps** [comment]
Interested

**Comment by Koira-Pupu** [comment]
Give me my invite pretty pleaze

**Comment by raymand211092** [comment]
Me 🇨🇺

**Comment by ciao1092** [comment]
> Interested? Leave a note on here

A note on here

**Comment by hxv** [comment]
A note.

**Comment by Klairm** [comment]
interested

**Comment by AntsyBoi** [comment]
I'm also interested

**Comment by s00ner** [comment]
Interested.

**Comment by f0rky** [comment]
Interested!

**Comment by Titaniumtown** [comment]
Interested!

**Comment by jfml** [comment]
Interested as well! (I actually have an account but the pw isn't working and don't have access to recovery email anymore 🤦‍♀️)

**Comment by SangeloDev** [comment]
i'd love to try this out, count me in!

**Comment by mugiishiro** [comment]
very much interested !

**Comment by scapehips** [comment]
Hey I am also interested in this

**Comment by IdotMaster1** [comment]
of course!!

**Comment by timmycodesforfun** [comment]
interested in beta testing :)

**Comment by ZeroSoundsCool** [comment]
please !

**Comment by Patel-Aman** [comment]
Interested

**Comment by Elijacobson1** [comment]
Yes plsss!

**Comment by timmycodesforfun** [comment]
interested in beta testing! still got a libre.fm account.

thanks a lot for your work.

**Comment by ponfertato** [comment]
It's a pity that registration was closed, pending opening!

**Comment by carlossgv** [comment]
Interested in beta testing!

**Comment by sahil-sagwekar2652** [comment]
Would love to help with beta testing. FOSS ftw

**Comment by lelsene** [comment]
👀

**Comment by UnagiCodes** [comment]
Interested!  I just missed your email :(

**Comment by dphillips479** [comment]
Still need more web-devs? I mostly work with TYPO3 (which borrows a lot from symphony), but also have some lavavel experiance.

I just stumbled over this project and researched for the last half hour. But since I not at all familiar with gnu-fm or anything related, I can't really tell just of how much help I can be. But if you need help, I can keep an eye on the project and look out for things I can contribute to.

**Comment by Jarshvor** [comment]
Interested. No rush. and thanks for taking the time with this.

**Comment by MEGA-Dawg68** [comment]
I am interested in this project!

**Comment by MEGA-Dawg68** [comment]
Hey I am still interested. I run Fedora 39 (Doesn't say in the website)
https://aboutmybrowser.com/billowing-pine

**Comment by senolfndk** [comment]
I want to subscribe

**Comment by FlitPix** [comment]
Still interested! I use Arch Linux (`Linux 6.7.9-arch1-1`) and Firefox 123.0.

**Comment by phong-nt** [comment]
big fan of the work. Please let us know when registration is open again. I use Windows and Android for music playing.

**Comment by k4u5hik** [comment]
I am interested https://aboutmybrowser.com/billowing-water

**Comment by AntsyBoi** [comment]
I'm also still interested

For desktop computer: 
- OS: Pop!_OS (Ubuntu Linux based) 22.04
- Browser: Brave

For mobile:
- Device: Pixel 7
- OS: GrapheneOS
- Browser: Vanadium or Brave

**Comment by alci987** [comment]
I'm very interested.

**Comment by millette** [comment]
My details are there: <https://github.com/foocorp/hacienda/issues/2#issuecomment-2004044817>

**Comment by powerdoll** [comment]
i'm interested i use Arch linux and Rhythmbox player

**Comment by catarial** [comment]
interested! https://aboutmybrowser.com/fancy-surf

**Comment by bluebeargreen-2** [comment]
I am interested https://aboutmybrowser.com/falling-queen

**Comment by nolemoczij** [comment]
+1
https://aboutmybrowser.com/broken-salad
win10
android 14 + chrome

**Comment by caden-parajuli** [comment]
I'm definitely interested https://aboutmybrowser.com/little-tooth.

OS: GNU Guix System
Device: Dell Precision 7510

**Comment by Flooralia** [comment]
Interested!  
Browser: Chrome 122.0.0.0
OS: Windows 10      
https://aboutmybrowser.com/silent-surf

**Comment by akhileshjain27** [comment]
Interested!! 

OS: MacOS and iOS 
Firefox/Librewolf on both

https://aboutmybrowser.com/bitter-surf

**Comment by pbellchambers** [comment]
Interested.

OS: Windows 11, also iOS
Browser: Firefox, Safari

**Comment by catb0x** [comment]
count me in ^_^

OS: Windows 11, Windows, and occasionally iOS
Browser: Firefox, Brave

**Comment by Furdox** [comment]
meow :3

https://aboutmybrowser.com/small-butterfly

**Comment by mediapinta** [comment]
Browser: LibreWolf 124.0.1-1
OS: Ubuntu
(I also want to try on Rhythmbox)

**Comment by JetpackJackson** [comment]
Interested! Using Librewolf and Linux on laptop, Android and Mull+Firefox on phone!
https://aboutmybrowser.com/royal-forest the stats are messed up because Librewolf user agent spoofing lol

**Comment by dudedevs** [comment]
Yayyy definitely!

https://aboutmybrowser.com/delicate-moon

**Comment by herdivineshadow** [comment]
Browser: Firefox
OS: Windows 10 on laptop

**Comment by vtrian** [comment]
Looking forward to this :-)
Browser: firefox
OS: Linux (Endeavour OS)

**Comment by funkyblue** [comment]
Interested. 
Browser: Chrome and Firefox
OS: Windows 11 Canery and Linux (Zorin 17)

Not a user, but very interested to help beta test.

**Comment by tahirhussain0909** [comment]
Interested

**Comment by tortuguitado** [comment]
i'm interested.

Browser: Firefox
OS: Windows 10

**Comment by patrikroy** [comment]
Interested.
Browser: Brave
OS: Windows 11

**Comment by AnvarTursunaliev** [comment]
I'm Interested

**Comment by Sonne3s** [comment]
I am interested https://aboutmybrowser.com/red-boat

**Comment by C6103** [comment]
https://aboutmybrowser.com/fragrant-snowflake interested

**Comment by klmelo** [comment]
Super interested!!!

https://aboutmybrowser.com/dark-bread

Void GNU/Linux

**Comment by muesqtk** [comment]
Interested 

https://aboutmybrowser.com/tight-mountain

pc/mobile

**Comment by danielfreire-dev** [comment]
Interested
https://aboutmybrowser.com/shiny-hall

**Comment by alessandroberna** [comment]
Interested, https://aboutmybrowser.com/holy-bush

**Comment by rritoque** [comment]
Interested. using Chromium in Ubuntu ARM . Thanks

**Comment by vladvolopes** [comment]
Interested. Firefox on Win11

**Comment by TronNerd82** [comment]
I'm interested. Firefox (not ESR) on Debian 12 Bookworm x86_64

**Comment by Left-Hand-Coder** [comment]
Looking forward to assisting when possible.

**Comment by SebastianChristen** [comment]
Interested!

OS: Windows 11, also Linux Mint
Browser: Firefox

**Comment by Moaaah** [comment]
Patiently waiting

**Comment by brollin** [comment]
Interested!

macOS 14.3, Firefox

**Comment by bennygoldman** [comment]
Interested!

Chrome on Intel Mac OS X 10_15_7

**Comment by xlados** [comment]
interested! Firefox on Linux x86_64

https://aboutmybrowser.com/tiny-tooth

**Comment by finnbechinka** [comment]
https://aboutmybrowser.com/dawn-glitter it says win 10 but i use 11

**Comment by ArminRetro** [comment]
#2 windows 10 and 11 and linux mint

**Comment by LalOpen** [comment]
Interested too! :)

**Comment by yaisatyan** [comment]
Interested...!
Linux (openSUSE Tumbleweed) and Firefox

**Comment by redfurbutt** [comment]
i am interested :3

**Comment by not-pedka** [comment]
[interested](https://aboutmybrowser.com/throbbing-recipe)

**Comment by Zoeytrope** [comment]
Yes, please! https://aboutmybrowser.com/cool-bread

**Comment by skydog10** [comment]
Yes, please. Browser: bing. Win 11. I redid my PC & put AIMP on it. It wants to connect to Libre FM. First I heard of your site & like listening. Thanks much

**Comment by justsomecanadianguy** [comment]
Definitely interested. Heard about through my music player, Strawberry.

**Comment by reo101** [comment]
+1; On NixOS, Android and MacOS; Stock Firefox 126.0; YT Music, Soundcloud, Spotify, MPD

**Comment by joshinha** [comment]
I'm interested

my operational systems are

android 14 and windows 11

thanks!

**Comment by sdcaulley** [comment]
https://aboutmybrowser.com/bitter-wave

Using Strawberry as my primary player.

**Comment by 0b1kn00b** [comment]
[https://aboutmybrowser.com/noisy-truth](https://aboutmybrowser.com/noisy-truth)

Coming back to scrobbling after years, I'm using syncthing on android/linux/windows and looking for a database cross platform (and open)

**Comment by bloomtronzero** [comment]
Laptop
Win 11, Chrome/Firefox/Edge(yes all of them)
Extensions, win32 apps, UWP apps, whatever you're cookin'

Also

Fedora Linux & SteamOS

Also

Pixel
Android 14 beta

**Comment by girlmaya** [comment]
@0b1kn00b 
> Coming back to scrobbling after years, I'm using syncthing on android/linux/windows and looking for a database cross platform (and open)

You might be interested in [maloja](https://github.com/krateng/maloja)

**Comment by qu4ntik** [comment]
Yo, i'm interested !
Windows 11 on Firefox fork (Mercury) 115.0
https://aboutmybrowser.com/damp-frost

**Comment by petsud** [comment]
Yes please.

Browser Name	Chrome (Thorium Browser)
Browser Version	124.0.0.0
Operating System	Linux x86_64
Language	en-US
Javascript	Enabled
Cookie Enabled?	true

**Comment by barraIhsan** [comment]
Interested, media player: foobar / ncmpcpp (wsl) & poweramp (android)
https://aboutmybrowser.com/black-thunder

**Comment by ImMALWARE** [comment]
Chrome on Windows 10
Browser Name	Chrome
Browser Version	126.0.0.0
Operating System	Windows 10
Language	ru-RU
Javascript	Enabled
Cookie Enabled?	true

**Comment by Mat0uz** [comment]
Interested!

Browser Name 	Firefox
Browser Version 	128.0
Operating System 	Linux x86_64(fedora 39), Android 13
Language 	en-US
Javascript 	Enabled
Cookie Enabled? 	true

**Comment by Kanishk-TheGreat117** [comment]
Interested 

Browser Name : Firefox 
Browser Version : IDK 
OS : Linux 64 Bit Fedora 40,
Language : en-IN
javascript : idk whether it is enabled or not

**Comment by peterweissbier** [comment]
YES

Browser Name 	Firefox
Browser Version 	128.0
Operating System 	Linux x86_64
Language 	en-US
Javascript 	Enabled
Cookie Enabled? 	true
Browser Size 	1920 x 881 px
Screen Size 	1920 x 1080 px

**Comment by inan-hira** [comment]
Count me in, please!

Up-to-date Firefox user on macOS, Ubuntu and Debian devices.

**Comment by its-ojas** [comment]
Count me in

**Comment by daedalus410** [comment]
I'm waiting. please count me in

**Comment by Parakovsky** [comment]
am  a music director of schopenhauer dot fm the exerimental multi media project and want to integrate my system with libre fm to display the replay counts and possibly make some ratings out of it.

**Comment by JBloom91** [comment]
I'd also love to get in.
Windows, PC, Firefox

**Comment by MForrest00** [comment]
Let me in!
PC, Brave and Vivaldi
Samsung S24+
Samsung A9+

**Comment by marcoj** [comment]
I'd like to jump onboard!

Laptop
https://aboutmybrowser.com/delicate-darkness
(says intel, but it's macbook m1 w/ osx 14.6.1)
also other browsers like Chrome, Librewolf, Safari, ...

plus iphone 12 mini w/ ios 17.5.1

**Comment by lyfja** [comment]
Definitely interested

Fedora Linux and Firefox https://aboutmybrowser.com/frosty-boat
Motorola Edge 40 with Android 14

**Comment by majerich** [comment]
Very interested

Laptop on EndevourOS using Strawberry + Tidal
Pixel 8 Pro on Android beta track

**Comment by Davercade** [comment]
Hello :-) greetings from Ireland - Linux - Manjero, PopOS, W11 (work only), Samsung S22 - scrobbling from Pano Scrobbler to ListenBrainz and Last.fm! Love to be included at some stage!

**Comment by StormLight14** [comment]
Super interested!

Arch Linux, Firefox 129.0

**Comment by yommish** [comment]
Interested here!

https://aboutmybrowser.com/sparkling-truth

Safari on CPU iPhone OS 17_5_1 like Mac OS X

**Comment by simplymathematics** [comment]
pixel 8a and Plexamp. Firefox on Android. https://aboutmybrowser.com/icy-truth

**Comment by MxEggSalad** [comment]
quite interested!!

Laptop/PC Desktop
Fedora Linux 40
6.10.6-200.fc40.x86_64

**Comment by Maskafou** [comment]
I'm in !!! \°0°/

**Comment by sadtab** [comment]
Interested as f*k

**Comment by mattl** [comment]
So I’m going to open up registration again. 

To get an invite ahead of time send me an email to mattl@mattl.dev with your GitHub username in the body of the email and subject line “Banana Co” — I’ll be sending out invites this week and reopening registration in early November. 

Please note. If you have your own mail server and can’t get your account working I don’t want to hear about it. Similarly username changes will not be handled. 

If you wish to contribute to Libre.fm you can donate via https://libre.fm/donate.php but that’ll have no affect on your account. More news on this change will come. This issue is now closed. No future beta testers will be admitted.

**Comment by mattl** [comment]
Registration is now open to issue 1 

https://libre.fm/register.php?foo=alpha
