### ISSUE TITLE
libre.fm down?

### ISSUE THREAD

**Issue by millette** [foocorp/hacienda#11]
Hi,

I know hacienda is only in planning, but today I've received errors playing songs, to find out <https://libre.fm/> is down. Is it a planned outage? Will it be back?

Thanks!

**Comment by millette** [comment]
> we are bored in the city

I can now login and then... nothing :-)

Well, UI wise. But it seems like it is accepting scrobbles again. Curious where this will lead.

**Comment by mattl** [comment]
Scrobbles should work, but we’re being hammered by some rogue traffic lately. The web UI isn’t dead but is very broken. Also heavily cached. 

Can you post a link to your profile?

**Comment by millette** [comment]
Oh <https://libre.fm/user/robinmillette> that works. After login, I was left on the frontpage with no links to follow. Didn't even think to check my page directly.

Thanks for the service, as always!

**Comment by mattl** [comment]
I think if you give the front page a few refreshes you’ll see a link. I have something to fix there (temporary hack)

I can promise that Hacienda will make all of this stuff better and easier but I need to actually find time to write something. I will get on that soon I hope.
