### ISSUE TITLE
Investigate libravatar.org

### ISSUE THREAD

**Issue by mattl** [foocorp/hacienda#15]
https://social.coop/@libravatar@photog.social/111884365780164303

**Comment by mattl** [comment]
@foocorp/beta-testers tell me if you have an existing [Gravatar](https://www.gravatar.com), try putting your email address in the form here: https://www.libravatar.org/tools/check/

**Comment by kkiris** [comment]
libravatar shows my gravatar on there just fine if i enter my email. did you just want us to 👍 if it worked?

**Comment by mattl** [comment]
That sounds good. And if you don't see your gravatar, please leave a comment with your Libre.fm username so I can investigate.

**Comment by pluc** [comment]
Gravatar shows up

**Comment by virtadpt** [comment]
Same.

**Comment by mattl** [comment]
Now using Libravatar.org (we'll see how it goes)
