### ISSUE TITLE
older clients only support HTTP

### ISSUE THREAD

**Issue by mattl** [foocorp/hacienda#17]
Seems like some clients, including foobar2000 only support posting to Libre.fm over HTTP, instead of modern-HTTPS.

Would be good to get a list of clients that only support HTTP.

**Comment by mattl** [comment]
Not a dumb question, in the case of Foobar2000 I think it's the scrobbling component. I'm going try and get access to a place where I can test Windows clients in future.

**Comment by mattl** [comment]
We should also look for updated versions of plugins that support Last.fm, Listenbrainz, etc. They might also support Libre.fm or be easily updated.

**Comment by janerationx** [comment]
Never mind. You beat me to it!

**Comment by jbwharris** [comment]
> There is a foo_audioscrobbler component that was last updated in 2022 and probably uses HTTPS. Is there a way to make it send scrobbles to Libre? We used to do that back in the day, remember?

I know I spoke with the dev for DEADBEEF ages ago about this and he basically said the plugin just needed to be pointed to a different API endpoint. So I'd imagine it would be similar with Foobar2000.

**Comment by mattl** [comment]
#38 handles this now
