### ISSUE TITLE
Beta testers for when we're ready (please comment with your operating system, device type... use https://aboutmybrowser.com/ to do this easily. Also let me know if you have *any* familiarity with a Unix command line and/or the Ruby language)

### ISSUE THREAD

**Issue by mattl** [foocorp/hacienda#2]
Libre.fm user mginco offered to beta test.

**Comment by gergelypolonkai** [comment]
Count me in 👍

**Comment by trashcatt** [comment]
I'd love to help.

**Comment by egecelikci** [comment]
I would like to 😤

**Comment by unseenlarks** [comment]
count me in please.

**Comment by fizzyarthur** [comment]
I'd like to participate in testing please.

**Comment by yewscion** [comment]
Likewise, would love to help out with testing.

**Comment by pgbito** [comment]
I'll be happy to help, let me know if i'm in

**Comment by s-light** [comment]
beta test welcome

**Comment by nlegaillart** [comment]
will be glad to help, can't wait to replace my old GNU FM instance!

**Comment by gitalosh** [comment]
Very keen to help.

**Comment by ipkpjersi** [comment]
I'd also like to help test.

**Comment by alxtrnr** [comment]
Happy to have the opportunity to help with testing.

**Comment by Nyabinary** [comment]
Same here

**Comment by millette** [comment]
I will migrate, sure!

**Comment by AyanoKiru** [comment]
can i join now?

**Comment by simonives** [comment]
Happy to be a tester too.

**Comment by Mindcool25** [comment]
I would love to beta test

**Comment by IsMeNick** [comment]
Count me in :D

**Comment by penglyn** [comment]
100% down for this!

**Comment by tarjeiba** [comment]
I'd be happy to be a tester.

**Comment by lisathejoyful** [comment]
same here ^

**Comment by xerz-one** [comment]
Heya! Just stumbled upon this, looks worth a try!

**Comment by axwax** [comment]
I'd love to test too!

**Comment by Vjay15** [comment]
me too :D

**Comment by Vestal-1** [comment]
I'd love to help. User u473t8 in LibreFM :)

**Comment by mattl** [comment]
Just a note to beta testers. I hope to have some initial (non-functional) designs to share in the next few weeks.

**Comment by thedeathstar** [comment]
Interested in testing for beta when available.

**Comment by well-it-wasnt-me** [comment]
interested !

**Comment by soarn** [comment]
Lets do it!

**Comment by stardustspirit** [comment]
i'm also interested!

**Comment by MinakoDev** [comment]
I'm interested.

**Comment by Shabinder** [comment]
+1

**Comment by driftywinds** [comment]
I am interested in the beta

**Comment by pvnkrockjesvs** [comment]
interessed to test the beta

**Comment by grdryn** [comment]
I'm interested to help test and provide feedback :heart:

**Comment by mpldr** [comment]
I'll help testing!

**Comment by gvxvik** [comment]
count me in

**Comment by averyterrel** [comment]
interested

**Comment by qcmoff22** [comment]
Nice job !

**Comment by michaelpennington** [comment]
Would love to help beta test

**Comment by urkbio** [comment]
i want to try libre.fm

**Comment by Dhruvarshim** [comment]
Hi, I would like to join the community too!

**Comment by jasondmoss** [comment]
Willing and able! Sign me up!

**Comment by louisgrasset** [comment]
Hey, I’d like to participate too

**Comment by kvltyapka** [comment]
Count me in

**Comment by BNH440** [comment]
I'd also like to help out

**Comment by girlmaya** [comment]
Hi

**Comment by tandav** [comment]
I'd like to test the new version too

**Comment by Shianiiiu** [comment]
Im here! Count me in PLZ.Id like to help test.

**Comment by Badgerr** [comment]
I am in.

**Comment by limcosta** [comment]
I would like to

**Comment by faq0** [comment]
Interested

**Comment by voyager** [comment]
An experienced beta tester here.

**Comment by not-tobo** [comment]
I would love to help testing :p

**Comment by Droppisalt** [comment]
Would love to help test :)

**Comment by mattl** [comment]
I have put up the first of (many) prototypes. https://github.com/foocorp/hacienda/issues/12

**Comment by janerationx** [comment]
Would love to beta test.

**Comment by mattl** [comment]
I have posted some thoughts on how login should work #13

**Comment by MannuVilasara** [comment]
count me in

**Comment by ea-st** [comment]
Willing to help!

**Comment by SelormDev** [comment]
I'm also interested!

**Comment by mattl** [comment]
Some thoughts on user profile pages: #14

**Comment by dacmail** [comment]
I want to test it!

**Comment by alessandroseni** [comment]
Interested in beta testing

**Comment by shmustin** [comment]
I would be interested. Thanks!

**Comment by dramonroca** [comment]
Same here

**Comment by mattl** [comment]
Played around with deploying Rails apps today. Built a new Ubuntu server and here we are: https://rails-demo.libre.fm — code is https://github.com/foocorp/rails-demo but this is basically just a default Rails app with a tiny bit of code from a tutorial… but I was able to do this all by myself in about 4 hours. Feeling good about it. 

Hacienda will be a series of small Rails apps I think so I can deploy pieces in different places. For example, we don’t need a lot of resources for just resetting passwords :)

It’s not much but it’s the first new thing on the libre.fm domain name for some time. Beta testers, leave an emoji on this comment when you’ve had a chance to check it out.

**Comment by nyabinary** [comment]
> Played around with deploying Rails apps today. Built a new Ubuntu server and here we are: https://rails-demo.libre.fm — code is https://github.com/foocorp/rails-demo but this is basically just a default Rails app with a tiny bit of code from a tutorial… but I was able to do this all by myself in about 4 hours. Feeling good about it.
> 
> Hacienda will be a series of small Rails apps I think so I can deploy pieces in different places. For example, we don’t need a lot of resources for just resetting passwords :)
> 
> It’s not much but it’s the first new thing on the libre.fm domain name for some time. Beta testers, leave an emoji on this comment when you’ve had a chance to check it out.

Isn't rails bad for scaling?

**Comment by mattl** [comment]
Not especially, 37signals just released a chat application that can support hundreds of concurrent users chatting on a machine with just 2Gb RAM. 

Libre.fm right now runs on two machines with 4GB RAM plus a database server. We use caching effectively too.

**Comment by prk0ghy** [comment]
Very testing much awaiting account. No honestly an account would be great. I will see if I can help in any way shape or form.

**Comment by themidnightmaniac** [comment]
Count me in!

**Comment by jvresol** [comment]
I'd also like to help test!

**Comment by szfkamil** [comment]
Happy to test actively!

**Comment by jfml** [comment]
Yes, please!

**Comment by IGS-GIT** [comment]
Here to test

**Comment by scapehips** [comment]
I would love to be a tester as well!

**Comment by dellmark100** [comment]
I want to beta

**Comment by MTLVMPR** [comment]
Would love to try it

**Comment by i1li** [comment]
Hello and God bless!

**Comment by teethenamel** [comment]
interested

**Comment by gitalosh** [comment]
Very interested to assist with BETA.

**Comment by PeterGeeza** [comment]
Interested

**Comment by nyabinary** [comment]
https://aboutmybrowser.com/delicate-grass

**Comment by unseenlarks** [comment]
https://aboutmybrowser.com/mute-wind

**Comment by scapehips** [comment]
https://aboutmybrowser.com/flat-river the data it collected is wrong though. I am on win11, screen is 1080p, my edge is on ver122.0.2365.80

**Comment by virtadpt** [comment]
https://aboutmybrowser.com/morning-wave

**Comment by grdryn** [comment]
- [x] https://aboutmybrowser.com/wild-wave
- [x] Lots of unix command line experience (Bash on Linux)
- [ ] Very minimal Ruby knowledge

**Comment by kir68k** [comment]
Still willing to help with testing
- [Browser info](https://aboutmybrowser.com/red-heart)
    - Librewolf changes the useragent, I'm on Linux x86_64
- Have some experience with Linux/BSD command line
    - Bash, setting up a server with ZFS, some Nix usage, some Nginx/Caddy knowledge
- No experience with Ruby/Rails

**Comment by Shabinder** [comment]
- Browser Info: https://aboutmybrowser.com/summer-unit
  - Have experience with unix shell, been maintaining servers, etc.

**Comment by jasondmoss** [comment]
I'm still in for testing:

[About My Browser](https://aboutmybrowser.com/steep-pond)

**Comment by perbehaps** [comment]
I'd like to beta test.

**Comment by sh1vvy** [comment]
I'm in for testing this out.

[About My Browser](https://aboutmybrowser.com/falling-cake)
*Chrome on Windows 11 Insider.

**Comment by XPhO3NiX11** [comment]
I'd like to beta test

**Comment by fam007e** [comment]
I'd like to beta test
OS: Debian 12
Browser: Brave

**Comment by AntsyBoi** [comment]
I'm also interested in beta testing, and I'm familiar with UNIX-like command line environments.

For desktop computer: 
- OS: Pop!_OS (Ubuntu based) 22.04
- Browser: Brave
For mobile:
- Device: Pixel 7
- OS: GrapheneOS
- Browser: Vanadium or Brave

**Comment by alci987** [comment]
'm interested. I use Linux, I have knowledge of Shell Script but not Ruby but Python

**Comment by millette** [comment]
**PopOs** (Ubuntu 22.04) with `wmii` here. I love my [alacritty terminal](https://alacritty.org/) and bash, it's where I spend most of my day.

Currently using Chrome but sometimes Firefox too. Details: <https://aboutmybrowser.com/lively-cell>.

**Comment by AdamK2003** [comment]
Still interested!
I know my Unix command line, no experience with Ruby though.
Browser info: https://aboutmybrowser.com/snowy-term
Additional system info:
```
OS: Arch Linux x86_64
Host: 82B5 Lenovo Legion 5 15ARH05
Kernel: 6.8.1-zen1-1-zen
Shell: zsh 5.9
WM: awesome
Terminal: WezTerm
```

**Comment by fizzyarthur** [comment]
Interested in testing.

OS: Kubuntu 23.10
Device: x86 laptop
Browser: Firefox 123
Screen: 1920x1080 15.6"

No familiarity with command line nor Ruby.

**Comment by dzpwl** [comment]
i distrohop a bit but i primarily use trisquel 11 on my desktop and antix 22 on my laptop, running librewolf on both. my only experience with the command line is some scripts for personal use, but i'd be willing to step it up a bit

**Comment by stinerman** [comment]
https://aboutmybrowser.com/damp-wood

I run Debian Stable.

I'm a command line novice, but have been using some Linux distribution for 20ish years.

**Comment by grwthomps** [comment]
I am interested in testing!

- **Operating systems I can test on (have access to):** 
  - Windows 11
  - macOS Sonoma (primary device)
  - Arch Linux
- **Browsers:** Any (I primarily use Firefox but can test on any)
- **Monitor:**
  - 27" 2560 x 1440 (primary) 
  - 16" 3456 x 2234 (macbook built-in display)
- **Mobile:** iPhone 15 Pro Max

I have **_some_** familiarity with both Ruby and command line, though I'm definitely a bit rusty on Ruby.

- **Ruby:** I understand basic methods, iterators, and principles of OOP
- **Command line:** basic operations like traversing directories, copying and moving files, basic git usage. No scripting experience.

**Comment by jeffiscow2** [comment]
I'm interested in testing.

https://aboutmybrowser.com/young-limit

OS:

-  Fedora workstation (whatever the latest version)
- Windows 11 Pro

**Comment by lzbk** [comment]
I'm interested in testing… Hopefully I'll have time to do so.
I mostly scrobble using an old ampache instance on an old Debian (but I might update).
My workstation is a [linux mint 21.3 on which I use firefox](https://aboutmybrowser.com/sparkling-king)

**Comment by kentukr** [comment]
Добавьте меня

**Comment by naymello** [comment]
count me in
https://aboutmybrowser.com/green-voice

**Comment by themidnightmaniac** [comment]
yoyo
https://aboutmybrowser.com/rapid-glade
I use arch btw!
I also know a good bit about unix.

**Comment by Lid9406** [comment]
WOOT!

Win10, MacOS (whatever the latest is), Android, iOS, iPadOS
(Don't get much deeper than user-level anymore, but willing to be a beta guinea pig!)

**Comment by onurebe** [comment]
https://aboutmybrowser.com/restless-salad

**Comment by candideu** [comment]
https://aboutmybrowser.com/soft-grass

**Comment by dubsmachine** [comment]
would love to beta test please.
I am using Windows 11 / Mac Sonoma / Ios 17.5 and Android 15

**Comment by johanbring** [comment]
Would it be cool to use Nostr-accounts as a user database and maybe to store data in?
I’d love to join. I run ubuntu, osx, windows and iOS.

**Comment by johanbring** [comment]
> @johanbring No blockchain stuff.

OK, maybe nice to skip that shit. I'd love to join anytime. 
I've been running a small indie label since early 2000 releasing my bands and some others. I took down the full catalogue from Spotify some month ago. It's insane to let a bunch of inbetween companies strip the money from the musicians as well as not letting them see who listens to them and keep that data for themselves etc. I'm really up for anything that is open source that lets musicans and listeners interact directly.

**Comment by eddiefive** [comment]
I might be late to the party; I want to help too!
https://aboutmybrowser.com/aged-cell

I am familiar with Linux, can't say I'm familiar with ruby as well.

**Comment by recou** [comment]
I would like too

https://aboutmybrowser.com/morning-flower

https://aboutmybrowser.com/throbbing-pine

experience with unix cli but not with ruby

**Comment by ShaggyDaddyDan** [comment]
im interested,
i use a windows 10 pc, and i also use a samsung galaxy s23
i also use and toy with all browsers except Firefox

**Comment by Sukinidachi** [comment]
https://aboutmybrowser.com/blue-grass
Windows 11 23H2 Build 22631.3527
Firefox 126.0b9
Desktop

**Comment by QuinnIwe** [comment]
Operating System: Arch Linux Rolling x86-64
Kernel: Customized 6.8.9 Linux
Host: ThinkPad L13 Yoga Gen 3 (Intel)
Browser: -O3 Built Chromium 126.0 & Firefox 125.0.3
DE/WM: GNOME & Hyprland
I am very familiar with the UNIX command-line

**Comment by ethCS** [comment]
interested
os - debian 12
unix cmd experience

**Comment by jcorporation** [comment]
I am interested in testing. I am the developer of [myMPD](https://github.com/jcorporation/myMPD) (a MPD web client) and want to integrate it.

**Comment by mepsd** [comment]
https://aboutmybrowser.com/autumn-mud

Browser Name	Chrome
Browser Version	124.0.0.0
Operating System	Linux x86_64
Language	en-GB
Javascript	Enabled
Cookie Enabled?	true
Browser Size	1850 x 932 px
Screen Size	1920 x 1080 px

**Comment by klmelo** [comment]
Interested in becoming a beta tester!
https://aboutmybrowser.com/dark-bread

Computer Science student at Brazil's biggest and best federal university and a big open source enthusiast.

**Comment by mikeapuli** [comment]
https://aboutmybrowser.com/blue-paper

CLI all good, Ruby not so much. Please let me know if you'd like some help beta testing :)

**Comment by GordonZhang2024** [comment]
I 'd like to help.
```
Browser Name 	Firefox
Browser Version 	125.0
Operating System 	Linux x86_64 (Fedora KDE 40)
Language 	en-US
Javascript 	Enabled
Cookie Enabled? 	true
Browser Size 	2560 x 1283 px
Screen Size 	2560 x 1440 px
```
I'm  familiar with UNIX command line.

**Comment by tescolopio** [comment]
I would like to assist, I am familiar with Unix commands. I'm sure I could brush up on Ruby as well to help.
```
Browser Name	Edge
Browser Version	125.0.0.0
Operating System	Linux x86_64
Language	en-US
Javascript	Enabled
Cookie Enabled?	true
Browser Size	1912 x 930 px
Screen Size	1920 x 1080 px
```

**Comment by nobbydoo80** [comment]
yo quiero libre 
[](https://aboutmybrowser.com/red-surf)

**Comment by nobbydoo80** [comment]
https://aboutmybrowser.com/red-surf

**Comment by nobbydoo80** [comment]
https://aboutmybrowser.com/summer-glade
Yes I am familiar with Ruby. Not an expert but I can run a command line

**Comment by cequalspid** [comment]
Firefox on Linux x86_64
Arch Linux 
Strawberry music player
Can do command line, but not Ruby.

**Comment by TheLouD1** [comment]
Interested in testing 
user from last.fm who wants to leave it
`<html>
<body>

Browser Name | Chrome
-- | --
126.0.0.0
Windows 10
fr-FR
Enabled
true
1536 x 730 px
1536 x 864 px


</body>
</html>`

**Comment by prk0ghy** [comment]
Browser Name 	 Firefox
Browser Version 	 127.0
Operating System 	 macOS 13.6.7 apple silicon
Language 	         en-US
Javascript 	         Enabled
Cookie Enabled? 	 true

###

Unix cl                      yes
Ruby                         no

**Comment by bloomtronzero** [comment]
Count me in
AMB was a bit off so

Platforms I'd test on
Laptop
Win 11, Chrome/Firefox/Edge(yes all of them)
Extensions, win32 apps, UWP apps, whatever you're cookin'

Also

Fedora Linux & SteamOS

Also

Pixel
Android 14 beta

**Comment by SangeloDev** [comment]
I'm interested too!
https://aboutmybrowser.com/morning-mouse - Arch Linux, Pop!_OS and macOS too. I also have a Google Pixel 7 Pro with GrapheneOS.
I can use Bash, but haven't ever used Ruby beyond installing packages with `gem`.. Happy to help as much as I can though!

**Comment by petsud** [comment]
I'm want to beta.
https://aboutmybrowser.com/solitary-river

Browser Name Chrome (Thorium Browser)
Browser Version 124.0.0.0
Operating System Linux x86_64
Language en-US
Javascript Enabled
Cookie Enabled? true

**Comment by NikYolo1** [comment]
I am in! 
https://aboutmybrowser.com/restless-bonus

**Comment by berkantdu123** [comment]
I'm looking forward too, sysadmin here but not knowing ruby
https://aboutmybrowser.com/lingering-brook

**Comment by Gresh1234** [comment]
I would like to join too!
I'm mainly on Windows, but occasionally use Debian and am familiar with the command line.
I haven't worked with Ruby (yet) so I'm not familiar
https://aboutmybrowser.com/small-block

**Comment by emili-o** [comment]
Interested. Windows 11 and Mac OS (Silicon). Some familiarity with the Unix command line.

https://aboutmybrowser.com/throbbing-mode

**Comment by nhm91135** [comment]
I can do some testing if you like.
Using Ubuntu 22.04 LTS on AMD Ryzen ,  MacOs.  I use Windows but only as required.
CLI very proficient, I normally use Bash, but any shell is fine.
I have been employed as full-stack developer for more than 10 years in many languages. C++, Javascript, Python PHP... too many to list.
Ruby not so much but different languages are not too difficult to deal with.  
Would I be effective at a Ruby developer? Nope and I don't have that much time for this anyway.  
Can I read Ruby and understand it? Yes.
  Let me know.

**Comment by spoisseroux** [comment]
Mac OSX Sonoma 14.4 (Apple M1 Pro Chip)
Firefox 127.0.2 (64-bit)
https://aboutmybrowser.com/young-pond

Comfortable in CLI and familiar with Ruby

**Comment by cbraidwood** [comment]
Linux
Dell Latitude 7490
https://aboutmybrowser.com/nameless-pine

I can use the Unix command line but I am unacquainted with Ruby.

**Comment by inan-hira** [comment]
Firefox on macOS, Ubuntu and Debian on M3 and Intel MacBook pros.

Using both command line (daily) and Ruby (less frequently).

**Comment by guilherme8787** [comment]
I am in:
OS: Ubuntu 22.04 jammy
Kernel: x86_64 Linux 6.5.0-44-generic
CPU: AMD Ryzen 5 1500X Quad-Core @ 8x 3,5GHz
GPU: AMD/ATI Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
RAM: 16GB

**Comment by jhonalvarezsantander** [comment]
Soy usuario activo de Libre.fm
SO : Windows
CLI: Sí, me siento cómodo con ello.
Ruby: No

**Comment by jhonalvarezsantander** [comment]
https://aboutmybrowser.com/purple-sea

**Comment by DarkGamer9898** [comment]
I shall also be a beta tester for Libre.fm. Ready when you are.

**Comment by eatallyourdarlings** [comment]
I'm keen to help! Comfy with using CLI. Safari on Intel Mac OS X 10_15_7

**Comment by nicemicro** [comment]
Would love to participate and help!

I'm on Arch Linux, using FireFox. I am OK using the shell, never did Ruby, but know Python somewhat.

**Comment by arkag** [comment]
Happy to be a tester.

No real experience programming, but I've got DevOps, SRE, and containerization experience. I'd also be open to learning Ruby if truly necessary. Linux CLI experience as well, of course.

I've got Android, Windows 11, and MacOS. I use Arc and Firefox.

**Comment by kkiris** [comment]
I would love to test!&numsp;I'm familiar with Linux CLI, but not with Ruby.<br>
Chromium (Tempest):&numsp;https://aboutmybrowser.com/ancient-credit<br>Firefox (Floorp):&numsp;https://aboutmybrowser.com/fancy-butterfly<br>Chromium (Arc):&numsp;https://aboutmybrowser.com/icy-pond

**Comment by tufo09** [comment]
I would be happy to be a tester. I am familiar with the Unix CLI, but not with Ruby.

arch linux (my desktop pc) https://aboutmybrowser.com/bitter-dew

I also have an android phone.

**Comment by pchmykh** [comment]
Would like. Unix CLI ok, Ruby not ok, apple silicon laptop, Fedora workstation on pc.

**Comment by mattl** [comment]
Please see the latest update on https://github.com/foocorp/hacienda/issues/1

beta testers will be given priority.

**Comment by mattl** [comment]
Everyone on this issue should get an invite to the beta testers GitHub team :)

**Comment by mattl** [comment]
https://github.com/foocorp/hacienda/issues/35
