### ISSUE TITLE
Beta tester task: existing users, try and reset your password and let me know if you get an email.

### ISSUE THREAD

**Issue by mattl** [foocorp/hacienda#33]
@foocorp/beta-testers 

**If you have an account already**, please go to https://libre.fm/reset.php and enter your username.

If you don't have an account, this is important to be working before we send out new accounts. Please continue to wait for an account.

**If you get an email, please leave a thumbs up on this issue by clicking below. There's no need to leave a comment saying it worked.** 

If you **do not** get an email, please leave a comment below.

For anything else, please email me or make a new issue and tag me.

**Comment by millette** [comment]
I asked with both my username and email and got the mail both times. I didn't actually reset my password.

**Comment by virtadpt** [comment]
@millette Same.  I was going to wait a bit before seeing if the reset message hit my inbox (because hosting provider), but it's likely you're somewhere else.

**Comment by voyager** [comment]
> If you don't have an account, this is important to be working before we send out new accounts.

So, if we don't have an account yet, we don't have to do anything?

**Comment by mattl** [comment]
@voyager Correct. 

@jdoggmcsquishy86 Send me an email with your username and email address and I'll see if I can find it.

@millette @virtadpt Please leave a thumbs up, no need to leave a comment if it worked :)

**Comment by alxtrnr** [comment]
An email with further information has been sent to the email address associated with your profile. I never received an email. Username - monaxle. Could be an old email registered to my account which I no longer have access to. I can't find any place on the site to check that.

**Comment by mattl** [comment]
@alxtrnr Email me and we'll figure it out. I can see the email address in the database.

@fredbaty There's no account called that. Are you sure you already have an account?

**Comment by mattl** [comment]
Going to close this. Email me if you're having issues with your known existing account.

**Comment by alxtrnr** [comment]
The registered email could be ***@***.***

You change it to ***@***.***

Thanks

Alexander Turner
Tel: 077 0969 0638 | email: ***@***.***

Sent from Proton Mail Android

-------- Original Message --------

**Comment by mattl** [comment]
@alxtrnr Removed your posting here as it revealed your phone number but not your email address.. Please send me a new email, don't reply to this.

**Comment by mattl** [comment]
@jdoggmcsquishy86 Please send it in an email to me, see https://mat.tl for my email address.
