### ISSUE TITLE
Fix up blog

### ISSUE THREAD

**Issue by mattl** [foocorp/hacienda#45]
I've imported the WordPress.com blog into https://github.com/foocorp/blog.libre.fm

I'd love to get it looking like libre.fm does now and have it serve up our blog posts with the same URLs.

Ideally, we could get this ready for next weekend's weekly update post, but no real hurry on that.

**Comment by janerationx** [comment]
I like the new blog, although the background color is way too red/pink for me. Other users might like it, though.

**Comment by mattl** [comment]
Fixed the background, got the weekly blog post up.

**Comment by janerationx** [comment]
Thank you.

**Comment by soliloquier** [comment]
Hi, I just waned to know if you're still interested in getting blog.libre.fm moved to a static site? If so, how does using Hugo as the static site engine sound? You can write blogs in markdown and it's entirely static, plus you'd be able to host the entire site using just Github pages if you wanted to.

**Comment by mattl** [comment]
@soliloquier it's already a static site, using 11ty and Ghost for now right now.

**Comment by soliloquier** [comment]
Oh, alright then, thanks anyway.
