### ISSUE TITLE
Artist photo and album art issues

### ISSUE THREAD

**Issue by inan-hira** [foocorp/hacienda#49]
In the current design, the artist photos are overflowing their container. See the example from this [artist page](https://libre.fm/artist/Swallowed+Whole/):

![image](https://github.com/user-attachments/assets/f0522205-363a-4503-b2d3-9e458fb0f061)

Simply setting the image's width to 100% seems to fix the issue.

Also, in one of the album pages for that same band, the image src attribute uses a Flattr URL. I am not sure whether another field's value is used in this attribute or not, it could simply be that the wrong URL was added as the image URL in the first place.

![image](https://github.com/user-attachments/assets/0ea9c900-b1a1-4727-87c1-75804d44ad4e)

**Comment by mattl** [comment]
Fixed https://github.com/foocorp/end-times/commit/859b2cdfbb5f09f0f2b38a2c6ce80561980a8c4e
