### ISSUE TITLE
"socket timeout has expired" scrobbling error

### ISSUE THREAD

**Issue by unseenlarks** [foocorp/hacienda#51]
this might not belong here and/or might be a glitch, but Pano Scrobbler threw this error, followed by the url https://libre.fm/2.0/,socket_timeout=unknown

is it related to not being able to delete scrobbles? what does it mean?
thank you.

(edit: the track eventually scrobbled.)

**Comment by mattl** [comment]
Not sure what would cause that but that URL is a 404... so Pano isn't doing something right. Let us know if you keep seeing this.
