### ISSUE TITLE
User list columns issue in mobile

### ISSUE THREAD

**Issue by inan-hira** [foocorp/hacienda#56]
The user list columns overlap and make it harder to read and interact in a mobile browser (Firefox for Android, in this case).

![Screenshot_20241113-050530.png](https://github.com/user-attachments/assets/f55443e5-95a5-455c-9a8c-1f5b6e9866d3)

**Comment by mattl** [comment]
Oops. I’ll fix this tomorrow.

**Comment by mattl** [comment]
Fixed.
