### ISSUE TITLE
Homepage <-> User profile links

### ISSUE THREAD

**Issue by inan-hira** [foocorp/hacienda#57]
Hi.

I love the colours, and the simplicity of the new design!

I noticed that the username on the homepage is linked to the homepage. Wouldn't it be better if it takes the user to the user's profile? Because apart from that, there's no link that takes you to your profile.

![Screenshot of the username on the homepage](https://github.com/user-attachments/assets/9e1ea98a-38e1-4c8d-95f8-3df9b689bc59)

Similarly, the logo on the user profile is linked to the user profile page, which basically reloads the page. I'd expect it to take me to the homepage. Again, I couldn't find any links to take me to the homepage.

![Screenshot of the logo on the user profile page](https://github.com/user-attachments/assets/4a54152a-ab32-44ab-8da6-25fa031bd322)

Loosely related to the subject, having that user bar from the profile page on the homepage would be really handy.

What do you think?

**Comment by mattl** [comment]
So if you’re logged in the logo will take you to your profile page currently as does the link on the homepage with your username. 

There’s really not much on the homepage that would warrant showing it to someone who’s already logged in. Anything useful there should be available on the user profile. For example, a list of up to 250 users isn’t something that makes sense on my profile but a list of five-ten recently played songs seems like it could work.

**Comment by inan-hira** [comment]
> So if you’re logged in the logo will take you to your profile page currently as does the link on the homepage with your username.

The username on the homepage doesn't take me to my profile. It reloads the homepage.

**Comment by mattl** [comment]
Hm, okay that’s a bug. I’ll get that fixed.
