### ISSUE TITLE
Use a more specific hashtag in individual scrobbles' social media copy

### ISSUE THREAD

**Issue by inan-hira** [foocorp/hacienda#58]
The sharing feature for the individual scrobbles is great! I guess that might even be automated at some point. But even when it is not automated, it can create quite a noise in the timelines, if you are following a lot of libre.fm users. Muting a hashtag would be the solution, but the preset hashtags in the “Share this on social media” link (#librefm, #indieweb, #music, #shareopenly) are very generic. They are hashtags that I'd follow, so I wouldn't want to mute them.

Wouldn't it be nice if there was a more specific hashtag? These might be bad examples, but something along the lines of #LibreFmListens or #LibreFmScrobbles, perhaps? Then a user on the social media could mute that specific hashtag.

<img width="325" alt="Screenshot of the Share this on social media link" src="https://github.com/user-attachments/assets/3a1a9c55-b978-417f-b1d6-8846293cdba4">

**Comment by unseenlarks** [comment]
+1. earlier today i noticed that it leads to automated accounts on Mastodon (an example is the Music Feed account from newsmast, which follows the #music hashtag) boosting these 'i scrobbled' posts. which might be perceived as spam by some.

i agree with Inan re: more specific hashtags mentioning scrobbling; that way, people can block/mute if needed. #MyScrobbles? #NowScrobbling? #JustScrobbled?

thanks. :)

**Comment by mattl** [comment]
Spam accounts are going to happen, I’m afraid. However we’ll use case sensitive hashtags.

**Comment by unseenlarks** [comment]
bit random and this will date me, but wishing Mastodon had a built-in 'now playing' field for each post... much like LiveJournal used to have. how cool would it be, to add the current track on any given post, on a dedicated part of it even, like some instances show hashtags at the end, for example. ;)
