### ISSUE TITLE
Where's the music?

### ISSUE THREAD

**Issue by meyou69** [foocorp/hacienda#59]
I have Firefox 133 running from my Fedora 41 KDE Spin computer. I go to https://libre.fm/user/naturbrilian/scrobble/1733332639 and I wish to listen to the song. Nothing comes out of it.

How do I play the song? Do I have to press a button or something?

**Comment by meyou69** [comment]
Ok. I see.

Should probably make that clearer on the site, especially since the original libre.fm allowed you to play music previously.

Thank you

**Comment by mattl** [comment]
The amount of music we have to play is very small and the provider hosting it hasn't been working well so for now that's turned off.

**Comment by meyou69** [comment]
You know what? I can respect that.

Thank you for being honest. I sympathize for your cause.

I hope things go well for you and your project

**Comment by meyou69** [comment]
You know what? I can respect that.

Thank you for being honest. I sympathize for your cause.

I hope things go well for you and your project
